### PR TITLE
Implement 1.2 Release

### PR DESCRIPTION
**Pull request by eliweitzman**
New 1.2 Build with a bunch of new tweaks and tools, including:

- #44 
- #42
- #41 
- #5 
- #18

### CODE REVIEW

**Comment by eliweitzman** [comment]
Since I made a bunch of out-of-band readme adjustments, just need to figure out how to merge the changes into main without wrecking the 1.2 release

**Comment by eliweitzman** [comment]
Okay I think the merge inward worked, so readme and security files are now up-to-date on 1.2 branch.

**Comment by eliweitzman** [comment]
I'm going to move on to compiling and testing

**Comment by eliweitzman** [comment]
Fixed a quick bug discovered while testing in compile! (#48 )

**Comment by eliweitzman** [comment]
Installers built and kept in draft of release. Awaiting review, then merge.l

**Comment by eliweitzman** [comment]
All variants are officially in review with Microsoft Security...

**Review by TheDeadGPU — APPROVED** [review]
Approved!

**Comment by eliweitzman** [comment]
Sweet! Merging, and prepping for launch when Defender SmartScreen is cleared.

**Comment by TheDeadGPU** [comment]
Full Send!

image

**Pull request merged**
